src/Entity/Commit.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use App\Repository\CommitRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ApiFilter(SearchFilter::class, properties={"author": "partial"})
 * @ORM\Entity(repositoryClass=CommitRepository::class)
 */
class Commit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @var int
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     * @var string
     */
    private $comment;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $commitHash;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @var \DateTimeImmutable
     */
    private $createdAt;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getCommitHash(): ?string
    {
        return $this->commitHash;
    }

    public function setCommitHash(string $commitHash): self
    {
        $this->commitHash = $commitHash;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCreatedAtString(): string {
      return $this->createdAt->format('Y-m-d H:i:s');
    }

    public function isCommitHashEndingByNumber() : bool
    {
      return is_numeric(substr($this->commitHash,strlen($this->commitHash) - 1,1));
    }
}

src/Controller/IndexController.php
<?php

namespace App\Controller;

use App\Repository\CommitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class IndexController extends AbstractController
{
    /**
     * @Route("/index", name="index")
     */
    public function index(CommitRepository $commitRepository): Response
    {
        $commits = $commitRepository->findBy([],[],25);
        return $this->render('index/index.html.twig', [
            'controller_name' => 'IndexController',
            'commits'=> $commits,
        ]);
    }

  /**
   * @Route("/refresh", name="refresh")
   * @param VcsInterface $vcs
   * @return Response
   */
  public function refresh(CommitRepository $commitRepository): Response
  {
    return $this->redirectToRoute('index', ['refreshed' => $commitRepository->refresh()]);
  }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body lang="EN">
        {% block body %}{% endblock %}
    </body>
</html>

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nodejs/Node Commits{% endblock %}

{% block body %}
  <div class="container bg-white pb-3">
    <div class="sticky-top bg-white pb-3">
      <h2>Nodejs/Node Last commits</h2>
      <div class="row align-items-end">
        <div class="col-md-6">
          <label>Search by Author</label>
          <input id="findAuthor" class="form-control"/>
        </div>
        <div class="col-md-6">
          <a class="btn btn-primary float-end" href="{{ path('refresh') }}" role="button">Fetch from Api (Refresh)</a>
        </div>
      </div>
    </div>

    {% for commit in commits %}
      <div class="row dataRow {{ commit.commitHashEndingByNumber?'endedByNumber':'' }}"
           data-id="{{ commit.author | replace({' ':''}) | lower }}-{{ commit.commitHash }}">
        <div class="col-lg">
          <p><strong>Hash: </strong>{{ commit.commitHash }}</p>
        </div>
        <div class="col-md"><strong>Author</strong>
          <p>{{ commit.author }}</p></div>
        <div class="col-md"><strong>Last commit: </strong>
          <p>{{ commit.createdAtString }}</p></div>
        <div class="col-xl-12"><strong>Comment: </strong>
          <p>{{ commit.comment }}</div>
        </p>
      </div>
    {% endfor %}

    <div class="row d-none" id="no-results">
      <h3>Your search got no results</h3>
    </div>

  </div>
{% endblock %}

{% block javascripts %}
  {{ parent() }}

  {{ encore_entry_script_tags('js/commits') }}
{% endblock %}